<template>
  <div class="wrapper" ref="wb">
    <ul class="content">
      <li>测试滚动刷新1</li>
      <li>测试滚动刷新2</li>
      <li>测试滚动刷新3</li>
      <li>测试滚动刷新4</li>
      <li>测试滚动刷新5</li>
      <li>测试滚动刷新6</li>
      <li>测试滚动刷新7</li>
      <li>测试滚动刷新8</li>
      <li>测试滚动刷新9</li>
      <li>测试滚动刷新10</li>
      <li>测试滚动刷新11</li>
      <li>测试滚动刷新12</li>
      <li>测试滚动刷新13</li>
      <li>测试滚动刷新14</li>
      <li>测试滚动刷新15</li>
      <li>测试滚动刷新16</li>
      <li>测试滚动刷新17</li>
      <li>测试滚动刷新18</li>
      <li>测试滚动刷新19</li>
      <li>测试滚动刷新20</li>
      <li>测试滚动刷新21</li>
      <li>测试滚动刷新22</li>
      <li>测试滚动刷新23</li>
      <li>测试滚动刷新24</li>
      <li>测试滚动刷新25</li>
      <li>测试滚动刷新26</li>
      <li>测试滚动刷新27</li>
      <li>测试滚动刷新28</li>
      <li>测试滚动刷新29</li>
      <li>测试滚动刷新30</li>
      <li>测试滚动刷新31</li>
      <li>测试滚动刷新32</li>
      <li>测试滚动刷新33</li>
      <li>测试滚动刷新34</li>
      <li>测试滚动刷新35</li>
      <li>测试滚动刷新36</li>
      <li>测试滚动刷新37</li>
      <li>测试滚动刷新38</li>
      <li>测试滚动刷新39</li>
      <li>测试滚动刷新40</li>
      <li>测试滚动刷新41</li>
      <li>测试滚动刷新42</li>
      <li>测试滚动刷新43</li>
      <li>测试滚动刷新44</li>
      <li>测试滚动刷新45</li>
      <li>测试滚动刷新46</li>
      <li>测试滚动刷新47</li>
      <li>测试滚动刷新48</li>
      <li>测试滚动刷新49</li>
      <li>测试滚动刷新50</li>
      <li>测试滚动刷新51</li>
      <li>测试滚动刷新52</li>
      <li>测试滚动刷新53</li>
      <li>测试滚动刷新54</li>
      <li>测试滚动刷新55</li>
      <li>测试滚动刷新56</li>
      <li>测试滚动刷新57</li>
      <li>测试滚动刷新58</li>
      <li>测试滚动刷新59</li>
      <li>测试滚动刷新60</li>
      <li>测试滚动刷新61</li>
      <li>测试滚动刷新62</li>
      <li>测试滚动刷新63</li>
      <li>测试滚动刷新64</li>
      <li>测试滚动刷新65</li>
      <li>测试滚动刷新66</li>
      <li>测试滚动刷新67</li>
      <li>测试滚动刷新68</li>
      <li>测试滚动刷新69</li>
      <li>测试滚动刷新70</li>
      <li>测试滚动刷新71</li>
      <li>测试滚动刷新72</li>
      <li>测试滚动刷新73</li>
      <li>测试滚动刷新74</li>
      <li>测试滚动刷新75</li>
      <li>测试滚动刷新76</li>
      <li>测试滚动刷新77</li>
      <li>测试滚动刷新78</li>
      <li>测试滚动刷新79</li>
      <li>测试滚动刷新80</li>
      <li>测试滚动刷新81</li>
      <li>测试滚动刷新82</li>
      <li>测试滚动刷新83</li>
      <li>测试滚动刷新84</li>
      <li>测试滚动刷新85</li>
      <li>测试滚动刷新86</li>
      <li>测试滚动刷新87</li>
      <li>测试滚动刷新88</li>
      <li>测试滚动刷新89</li>
      <li>测试滚动刷新90</li>
      <li>测试滚动刷新91</li>
      <li>测试滚动刷新92</li>
      <li>测试滚动刷新93</li>
      <li>测试滚动刷新94</li>
      <li>测试滚动刷新95</li>
      <li>测试滚动刷新96</li>
      <li>测试滚动刷新97</li>
      <li>测试滚动刷新98</li>
      <li>测试滚动刷新99</li>
      <li>测试滚动刷新100</li>
      <li>测试滚动刷新101</li>
      <li>测试滚动刷新102</li>
      <li>测试滚动刷新103</li>
      <li>测试滚动刷新104</li>
      <li>测试滚动刷新105</li>
      <li>测试滚动刷新106</li>
      <li>测试滚动刷新107</li>
      <li>测试滚动刷新108</li>
      <li>测试滚动刷新109</li>
      <li>测试滚动刷新110</li>
      <li>测试滚动刷新111</li>
      <li>测试滚动刷新112</li>
      <li>测试滚动刷新113</li>
      <li>测试滚动刷新114</li>
      <li>测试滚动刷新115</li>
      <li>测试滚动刷新116</li>
      <li>测试滚动刷新117</li>
      <li>测试滚动刷新118</li>
      <li>测试滚动刷新119</li>
      <li>测试滚动刷新120</li>
      <li>测试滚动刷新121</li>
      <li>测试滚动刷新122</li>
      <li>测试滚动刷新123</li>
      <li>测试滚动刷新124</li>
      <li>测试滚动刷新125</li>
      <li>测试滚动刷新126</li>
      <li>测试滚动刷新127</li>
      <li>测试滚动刷新128</li>
      <li>测试滚动刷新129</li>
      <li>测试滚动刷新130</li>
      <li>测试滚动刷新131</li>
      <li>测试滚动刷新132</li>
      <li>测试滚动刷新133</li>
      <li>测试滚动刷新134</li>
      <li>测试滚动刷新135</li>
      <li>测试滚动刷新136</li>
      <li>测试滚动刷新137</li>
      <li>测试滚动刷新138</li>
      <li>测试滚动刷新139</li>
      <li>测试滚动刷新140</li>
      <li>测试滚动刷新141</li>
      <li>测试滚动刷新142</li>
      <li>测试滚动刷新143</li>
      <li>测试滚动刷新144</li>
      <li>测试滚动刷新145</li>
      <li>测试滚动刷新146</li>
      <li>测试滚动刷新147</li>
      <li>测试滚动刷新148</li>
      <li>测试滚动刷新149</li>
      <li>测试滚动刷新150</li>
      <li>测试滚动刷新151</li>
      <li>测试滚动刷新152</li>
      <li>测试滚动刷新153</li>
      <li>测试滚动刷新154</li>
      <li>测试滚动刷新155</li>
      <li>测试滚动刷新156</li>
      <li>测试滚动刷新157</li>
      <li>测试滚动刷新158</li>
      <li>测试滚动刷新159</li>
      <li>测试滚动刷新160</li>
    </ul>
  </div>
</template>

<script>
//引入better-scroll
import BetterScroll from 'better-scroll'

export default {
  name: "TestBetterScroll",
  data:function (){
    return{
      bscroll:null
    }
  },
  mounted() {
    console.log(this.$refs.wb);
    this.bscroll = new BetterScroll(this.$refs.wb,{
      //开始实时位置侦测
      probeType:3,
      //开始上拉刷新
      pullUpLoad:true
    })

    //监听实时位置
    this.bscroll.on('scroll',function (position){
      console.log(position);
    })

    //监听上拉加载
    this.bscroll.on('pullingUp',function (){
      console.log('上拉加载更多..');
    })
  }
}
</script>

<style scoped>
/*必须拥有一个固定高度的wrapper包裹滚动标签*/
  .wrapper{
    height: 150px;
    background-color: beige;
    overflow: hidden;
  }
</style>
